Website/Controllers/IMDBController.cs
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class IMDBController : Controller
    {
        //Gemaakt door: Timo Hoogendorp
        //Getest door: Arie Visser
        [HttpPost]
        public ActionResult IMDBMovie(string MovieName)
        {
            string IMDBMovieName = MovieName;

            IMDb imdb = new IMDb(IMDBMovieName, true);
            string Title = imdb.Title;

            if (imdb.Title != null)
                return View(imdb);
            else
                Session["foutmelding"] = ("Deze film is niet gevonden!");
                return View("~/Views/Shared/Error.cshtml");
        }
            //rest volgt vanavond!

  
        }
    }

Website/Controllers/MovieShowingsController.cs
using System.Linq;
using System.Web.Mvc;
using Domain.Models;
using Website.Models;
using Domain.Interfaces;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System;

namespace Website.Controllers
{
    public class MovieShowingsController : Controller
    {
        //Gemaakt door: Arie Visser
        //Getest door: Merel Huijben

        private readonly IMovieShowingsService _movies;
        public MovieShowingsController(IMovieShowingsService moviesShowing)
          {
            _movies = moviesShowing;
        }

    // GET: MovieShowings

    public ActionResult Movies(string Date)
        {

            var m = _movies.GetMovieShowings();

            if (Date == null){ Date = DateTime.Today.ToString("dd-MM-yyyy"); };

            var model = from movie in m
                        select new MovieShowingsModel
                        {
                            Id = movie.Id,
                            MoviesId = movie.Movies.Id,
                            MoviesIdFk = movie.MoviesId,
                            Info = movie.Movies.Info,
                            ImageData = movie.Movies.ImageData,
                            Name = movie.Movies.Name,
                            Genres = movie.Movies.Genres,
                            Plot = movie.Movies.Plot,
                            Duration = movie.Movies.Duration,
                            AgeRating = movie.Movies.AgeRating,
                            DateTime = movie.DateTime,
                            MovieTypes = movie.Movies.MovieTypes,
                            DateSelected = Date,
                            RoomNumber = movie.Rooms.RoomNumber
        };
            var DateSelected = Date;

            return View(model);

        }

        public ActionResult MoviesSelected(string Date, int id)
        {

            var m = _movies.GetMovieShowings();
            Session["UrlId"] = id;
            Session["UrlDate"] = Date;
            
            var id2 = Convert.ToInt32(Session["UrlId"]);


            if (Date == null) { Date = DateTime.Today.ToString("dd-MM-yyyy"); };

            var model = from movie in m
                        select new MovieShowingsModel
                        {
                            Id = movie.Id,
                            MoviesId = movie.Movies.Id,
                            ImageData = movie.Movies.ImageData,
                            Name = movie.Movies.Name,
                            Info = movie.Movies.Info,
                            Genres = movie.Movies.Genres,
                            Plot = movie.Movies.Plot,
                            Duration = movie.Movies.Duration,
                            AgeRating = movie.Movies.AgeRating,
                            DateTime = movie.DateTime,
                            MovieTypes = movie.Movies.MovieTypes,
                           // urlId = id,
                            DateSelected = Date,
                            RoomNumber = movie.Rooms.RoomNumber
                        };

            return View(model);

        }
    }
}

Website/Controllers/TicketController.cs
using System.Linq;
using System.Web.Mvc;
using Domain.Models;
using System.Data.Entity;
using Website.Models;


namespace Website.Controllers

{
    public class TicketController : Controller
    {
        //Gemaakt door: Arie Visser
        //Getest door: 
        private cinemaEntities1 db = new cinemaEntities1();

        // GET: Tickets
        public ActionResult Tickets(Movies model, MoviesShowings modelShowings)
        {
            Session["Moviename"] = model.Name;
            Session["MovieShowingsID"] = modelShowings.Id;

            var movieShowing = db.MoviesShowings.First(m => m.Id == model.Id);
            var allSeatIds = movieShowing.Rooms.Seats.Select(s => s.Id);
            var reservedSeatIds = movieShowing.Bookings.SelectMany(s => s.SeatsReserveds).Select(s => s.SeatId);
            var availableSeats = allSeatIds.Where(s => !reservedSeatIds.Contains(s)).Count();

            Session["AvailableSeats"] = availableSeats;

            ViewBag.Title = "Kies uw ticket(s)";
            ViewBag.Header = "Kies hier je ticket(s) voor: " + Session["Moviename"];

            var tickets = db.BookingTypes.Include(i => i.SeatsReserveds);
            var ticketOption = db.BookingOptionsSets.ToList();

            var movies = db.Movies.First(m => m.Name == model.Name);
            var movieType = movies.MovieTypes.Type;
            if (movieType == "3D")
            {
                TempData["3D"] = movieType;
            }
            else { TempData["3D"] = "Geen 3D!"; }

            var view = new TicketModel()
            {
                BookingTypes = tickets,
                BookingOptionsSets = ticketOption
            };


            return View(view);
        }
        public ActionResult TicketsSelected(int[] ticketKind, int[] totalTickets, int[] ticketOption, int[] totalOptionTickets)
        {

            //Gemaakt door: Arie Visser
            //Getest door: Merel Huijben


            //Gemaakt door: Arie Visser
            //Getest door: Merel Huijben

            var model = new Models.TicketsSelectedModel();
            var total = 0m; // Met d geef je aan dat het om een double gaat en met m een decimal (m staat voor money);
            var totalOptions = 0m;

            for (int i = 0; i < ticketKind.Count(); i++)
            {
                var ticketId = ticketKind[i];
                var bookingType = db.BookingTypes.First(b => b.Id == ticketId);
                var totalOrderedTickets = totalTickets[i];

                if (totalOrderedTickets > 0)
                {
                    model.ChosenTickets.Add(new ChosenTickets
                    {
                        TicketName = bookingType.Name,
                        TotalPrice = bookingType.Price.GetValueOrDefault(0) * totalOrderedTickets,
                        TotalOrdered = totalOrderedTickets,
                        TicketTypeId = ticketId,
                    });

                    total += bookingType.Price.GetValueOrDefault(0) * totalTickets[i];
                }
            }
            for (int o = 0; o < ticketOption.Count(); o++)
            {
                var ticketOptionId = ticketOption[o];
                var bookingOption = db.BookingOptionsSets.First(b => b.Id == ticketOptionId);
                var totalOrderedOptions = totalOptionTickets[o];

                if (totalOrderedOptions > 0)
                {
                    model.ChosenTickets.Add(new ChosenTickets
                    {
                        TicketOptionName = bookingOption.Name,
                        TotalOptionPrice = bookingOption.price * totalOrderedOptions,
                        TotalOptionOrdered = totalOrderedOptions,
                        TicketOptionTypeId = ticketOptionId,

                    });
                    totalOptions += bookingOption.price * totalOptionTickets[o];
                }
            }
            model.TotalPrice = total;
            model.TotalOptionsPrice = totalOptions;
            model.FinalPrice = total + totalOptions;

            ViewBag.Title = "Controle";
            ViewBag.Header = "Controleer uw bestelling!";
            Session["ChosenTickets"] = model;
            Session["TotalPrice"] = model.FinalPrice;

            return View(model);
        }
    }
}

Website/Views/MovieShowings/Movies.cshtml
@model IEnumerable<Website.Models.MovieShowingsModel>

@{
    ViewBag.Title = "Movies";
}
<div class="main">
    <div class="header_content">
        <div class="top-header">
            <div class="logo">
                <p>Selecteer de gewenste datum en tijd!</p>
            </div>
            <div class="search">
                @using (Html.BeginForm("IMDBMovie", "IMDB", FormMethod.Post))
                {
                    <input type="text" value="" name="MovieName" />
                    <input class="button" id="submit" type="submit" value="" />
                }
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="row" id="leftmargin">

            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.ToString("dd-MM-yyyy")})" class="btn btn-primary" type="button">Vandaag</a>


            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(1).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">Morgen</a>


            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(2).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(2).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(3).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(3).ToString("dddd dd MMMM")</a>

            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(4).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(4).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(5).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(5).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("Movies", "MovieShowings", new { Date = DateTime.Today.AddDays(6).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(6).ToString("dddd dd MMMM")</a>
        </div>
        <hr />
        <br />
        <br />
        
          @foreach (var item in Model.Select(i => i.Name).Distinct().ToList())
          {
              foreach (var movies in Model.Where(i => i.Name == item).Where(i => i.DateTime.ToString("dd-MM-yyyy") == i.DateSelected).Where(i => i.DateTime > DateTime.Now).GroupBy(i => i.Name))
              {

                    <div class="row">
                        <div class="col-md-3">
                          
                            <div class="thumbnail">
                                @foreach (var image in Model.Where(i => i.Name == item).Take(1))
                                {
                                    //if (image.DateTime.ToString("dd-MM-yyyy") != image.DateSelected)
                                    //{
                                        <img class="movie-image" src="@image.ImageData" />
                                    //<p>@image.DateTime.ToString("dd-MM-yyyy")</p>
                                    //<p>@image.DateSelected</p>
                                    //}
                                }
                            </div>
                        </div>
                        <div class="col-md-8">
                            @foreach (var info in Model.Where(i => i.Name == item).Take(1))
                            {

                            <h4>@info.Name</h4>
                            }
                            @foreach (var datetime in Model.Where(i => i.Name == item).Where(i => i.DateTime.ToString("dd-MM-yyyy") == i.DateSelected).Where(i => i.DateTime > DateTime.Now).ToList())
                            //@foreach (var datetime in Model.Where(i => i.Name == item).Where(i => i.DateTime.ToString("dd-MM-yyyy") == i.DateSelected && i.DateTime > DateTime.Today()).ToList())
                            {

                                <a href="@Url.Action("Tickets", "Ticket", new { Id = datetime.Id, Name = datetime.Name })">
                                    <button class="btn btn-primary" type="button">
                                        @datetime.DateTime.ToString("dd/MM - HH:mm") <span class="badge">@datetime.MovieTypes.Type</span>

                                    </button>
                                </a>
                                <p>Zaal: @datetime.RoomNumber @Html.Raw("-") @datetime.Info</p>
                              
                            }
                        </div>
                    </div>
                    <hr />
                  }

              
          }

    </div>

Website/Views/MovieShowings/MoviesSelected.cshtml
@model IEnumerable<Website.Models.MovieShowingsModel>

@{
    ViewBag.Title = "Movies";
}
<div class="main">
    <div class="header_content">
        <div class="top-header">
            <div class="logo">
                <p>Selecteer de gewenste datum en tijd!</p>
            </div>
            <div class="search">
                @using (Html.BeginForm("IMDBMovie", "IMDB", FormMethod.Post))
                {
                    <input type="text" value="" name="MovieName" />
                    <input class="button" id="submit" type="submit" value="" />
                }
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="row" id="leftmargin">

            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.ToString("dd-MM-yyyy")})" class="btn btn-primary" type="button">Vandaag</a>


            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(1).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">Morgen</a>


            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(2).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(2).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(3).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(3).ToString("dddd dd MMMM")</a>

            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(4).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(4).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(5).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(5).ToString("dddd dd MMMM")</a>


            <a href="@Url.Action("MoviesSelected", "MovieShowings", new { Date = DateTime.Today.AddDays(6).ToString("dd-MM-yyyy") })" class="btn btn-primary" type="button">@DateTime.Today.AddDays(6).ToString("dddd dd MMMM")</a>
        </div>
        <hr />
        <br />
        <br />

        @*@Session["UrlId"]*@

            @foreach (var item in Model.Select(i => i.Name).Distinct().ToList())
            {

                foreach (var movies in Model.Where(i => i.Name == item).Where(i => i.MoviesId == Convert.ToInt32(Session["UrlId"])).GroupBy(i => i.Name))
                {
                <div class="row">
                    <div class="col-md-3">
                        
                            
                           
                            <div class="thumbnail">
                                @foreach (var image in Model.Where(i => i.Name == item).Take(1))
                                {

                                    <img class="movie-image" src="@image.ImageData" />
                                }
                            </div>
                        </div>

                    <div class="col-md-8">
                        @foreach (var info in Model.Where(i => i.Name == item).Take(1))
                        {

                            <h4>@info.Name</h4>


                            foreach (var datetime in Model.Where(i => i.Name == item).Where(i => i.DateTime.ToString("dd-MM-yyyy") == i.DateSelected).Where(i => i.DateTime > DateTime.Now).ToList())
                            {

                                    <a href="@Url.Action("Tickets", "Ticket", new { Id = datetime.Id, Name = datetime.Name })">
                                        <button class="btn btn-primary" type="button">
                                            @datetime.DateTime.ToString("dd/MM - HH:mm") <span class="badge">@datetime.MovieTypes.Type</span>
                                        </button>
                                    </a>
                                    <p>Zaal: @datetime.RoomNumber @Html.Raw("-") @datetime.Info</p>

                                    }
                                    }



</div>
                </div>
                    <hr />
                    }
            }
    </div>